sudo: required

language: node_js

node_js:
  - "8"

dist: trusty

cache:
  directories:
    - node_modules

addons:
  chrome: stable

install:
  - npm ci

before_install:
  - npm install coveralls

script:
  - npm run test

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

before_deploy:
  - npm run build

deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
  skip_cleanup: true
